# Generated by Django 4.1.5 on 2023-01-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_auto_20221210_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='age',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
