# Generated by Django 4.1.5 on 2023-02-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0011_alter_bloodrequest_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='proof2',
            field=models.ImageField(blank=True, null=True, upload_to='proof/'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='proof3',
            field=models.ImageField(blank=True, null=True, upload_to='proof/'),
        ),
    ]
